### ISSUE TITLE
# ./bin/move executing a CLI Application defines a board variable

### ISSUE THREAD

**Issue by LeroyHutchinsonJ** [learn-co-curriculum/intro-to-cli-applications#9]
Not sure why this is happening, This is the code in my bin/move folder
#!/usr/bin/env ruby

require_relative '../lib/move.rb'

# Code your CLI Here
board =[" "," "," "," "," "," "," "," "," "]

puts "Welcome to Tic Tac Toe!"
puts "Where would you like to move"
input = gets.strip

input_to_index(input)

move(board,index, "X")

display_board(board)

This is the code in my lib/move.rb folder

def display_board(board)
  puts " #{board[0]} | #{board[1]} | #{board[2]} "
  puts "-----------"
  puts " #{board[3]} | #{board[4]} | #{board[5]} "
  puts "-----------"
  puts " #{board[6]} | #{board[7]} | #{board[8]} "
end

# code your input_to_index and move method here!

#Takes user input and uses it to fill out position that user inputed
def input_to_index(index)
trueIndex = index.to_i - 1
return trueIndex
end

def move(array, index, value = "X")
  trueIndex = index.to_i
  array[trueIndex] = value
end

**Comment by drakeltheryuujin** [comment]
Hi there,

[Raising issues on GitHub](http://help.learn.co/improving-learn/contributing-to-lessons/raising-an-issue-with-a-lab-or-lesson) should be reserved for problems with the curriculum — not difficulties solving a lab, mistakes fixed via [a quick edit](http://help.learn.co/improving-learn/contributing-to-lessons/can-i-edit-a-lesson), or bugs with the Learn platform (such as [lights not turning green](http://help.learn.co/your-learn-account/learn-lights/lights-not-turning-green) or [IDE issues](http://help.learn.co/the-learn-ide)).

In fact, there's a great article about this very issue over in the [Learn Help Center](http://help.learn.co/). Check it out! 🎉

If you still require assistance after reading the Help Center article, pop into [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ), where the [Technical Coaches](http://help.learn.co/instructional-support/receiving-course-support/who-are-the-technical-coaches) (on [supported tracks](http://help.learn.co/instructional-support/receiving-course-support/does-my-program-or-course-have-technical-coach-support)) and fellow community members can provide additional help. For some tips on how to take full advantage of AAQ, check out [this helpful article](http://help.learn.co/ask-a-question/how-to-optimize-time-in-ask-a-question) in the [Learn Help Center](http://help.learn.co/).

If, after consulting the Help Center and AAQ, you still feel that this is an issue with the curriculum itself, please reopen the issue and provide more detail about why it's a curriculum issue, the steps needed to reproduce the issue, and any additional relevant information about your development environment (local or IDE).

Thanks! 💙
